apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemonset
  namespace: default
  labels:
    k8s-app: test-daemonset
spec:
  selector:
    matchLabels:
      name: test-daemonset
  template:
    metadata:
      labels:
        name: test-daemonset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: test-daemonset
        image: nginx
        resources:
          limits:
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-daemonset
  namespace: default
  labels:
    k8s-app: test-deploy
spec:
  selector:
    matchLabels:
      name: test-deploy
  template:
    metadata:
      labels:
        name: test-deploy
    spec:
      containers:
      - name: test-deploy
        image: nginx
        resources:
          limits:
            memory: 100Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replica
  labels:
    app: test-replica
    tier: test-replica
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: test-replica
    matchExpressions:
      - {key: tier, operator: In, values: [test-replica]}
  template:
    metadata:
      labels:
        app: test-replica
        tier: test-replica
    spec:
      containers:
      - name: test-replica
        image: nginx
        resources:
          requests:
            memory: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-state
spec:
  selector:
    matchLabels:
      app: test-state # has to match .spec.template.metadata.labels
  serviceName: "test-state"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: test-state # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: test-state
        image: nginx
